apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: predtopic-svc-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: predtopic
  jobLabel: predtopic
  endpoints:
  - path: /metrics
    port: predtopic
    scheme: http
    interval: 5s