apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-config
  namespace: monitoring
data:
  config.yaml:
    rules:
      # Rule to map your Prometheus metric to a Kubernetes custom metric
      # Metric transformation rule
      - seriesQuery: 'rate(theft_dispute_reporting_total{endpoint="predtopic"}[5m])'
        resources:
          template: <<.Resource>>
        name:
          matches: "^(.*)_total$"
          as: "${1}_per_5min"
        metricsQuery: 'sum(rate(theft_dispute_reporting_total{endpoint!=""}[5m])) by (<<.GroupBy>>)'
